on:
  repository_dispatch
    
jobs:
  tf-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Investigate signal source
        env:
          REPO: ${{ github.event.client_payload.source }}
        run: echo "TF Build triggered by an update to the $REPO code"
      
      - name: Checkout the latest version of the TF code into the runner's fs
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure AWS credentials for TF cli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID__ghactionstfdeploy }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY__ghactionstfdeploy }}
          aws-region: eu-west-2

      - name: Setup TF 
        uses: hashicorp/setup-terraform@v2

      - name: TF Init
        run: terraform init

      - name: TF Apply
        run: terraform apply --auto-approve

      